export interface MobileTermInput {
  kw: string;
  zhCn: string;
  translations: Record<string, string>;
}

/**
 * Android XML Resource Generator (TASK-803)
 * Compiles strings into res/values-[locale]/strings.xml
 */
export class AndroidGenerator {
  public static escapeAndroidXml(str: string): string {
    if (!str) return '';
    return str
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll("'", "\\'")
      .replaceAll('"', '\\"')
      .replaceAll('\r\n', '\\n')
      .replaceAll('\n', '\\n');
  }

  /**
   * Normalize KW to Android string name (lower snake case, e.g. KW_RIDE_START -> kw_ride_start)
   */
  public static toAndroidName(kw: string): string {
    return kw.toLowerCase();
  }

  /**
   * Generate Android strings.xml content for a specific language
   */
  public generateXml(terms: MobileTermInput[], lang: string): string {
    const lines: string[] = [
      '<?xml version="1.0" encoding="utf-8"?>',
      '<!-- Auto-generated by glossa-cli (TASK-803) -->',
      '<resources>',
    ];

    for (const term of terms) {
      let text = term.translations[lang];
      if (text === undefined || text === '') {
        text = lang === 'zh' ? term.zhCn : term.translations['en'] || term.zhCn;
      }
      const name = AndroidGenerator.toAndroidName(term.kw);
      const escaped = AndroidGenerator.escapeAndroidXml(text);
      lines.push(`    <string name="${name}">${escaped}</string>`);
    }

    lines.push('</resources>');
    lines.push('');
    return lines.join('\n');
  }
}
