export interface CHeaderTermInput {
  kw: string;
  zhCn: string;
  translations: Record<string, string | undefined>; // lang -> text
}

export interface CHeaderGenerateOptions {
  projectName?: string;
  versionName?: string;
  targetLanguages?: string[];
}

export interface GeneratedCFiles {
  headerContent: string; // strings_lang.h
  sourceContent: string; // strings_lang.c
}

/**
 * C Language Code Generator (TASK-802)
 * Compiles glossary entries into ROM-optimized C header and lookup table (.h / .c)
 * Strict zero-warning GCC/Clang standard compliance.
 */
export class CHeaderGenerator {
  public static readonly DEFAULT_LANGUAGES = [
    'zh',
    'en',
    'de',
    'fr',
    'es',
    'it',
    'nl',
    'pl',
    'ja',
    'ko',
    'ru',
  ];

  /**
   * Escape C string literal
   */
  public static escapeCString(str: string): string {
    if (!str) return '';
    return str
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\r\n/g, '\\n')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\n')
      .replace(/\t/g, '\\t');
  }

  /**
   * Format language code to C Enum identifier (e.g. 'zh' -> 'LANG_ZH_CN', 'en' -> 'LANG_EN_US')
   */
  public static toLangEnum(lang: string): string {
    const map: Record<string, string> = {
      zh: 'LANG_ZH_CN',
      en: 'LANG_EN_US',
      de: 'LANG_DE_DE',
      fr: 'LANG_FR_FR',
      es: 'LANG_ES_ES',
      it: 'LANG_IT_IT',
      nl: 'LANG_NL_NL',
      pl: 'LANG_PL_PL',
      ja: 'LANG_JA_JP',
      ko: 'LANG_KO_KR',
      ru: 'LANG_RU_RU',
    };
    return map[lang.toLowerCase()] || `LANG_${lang.toUpperCase()}`;
  }

  /**
   * Generate strings_lang.h and strings_lang.c
   */
  public generate(
    terms: CHeaderTermInput[],
    options: CHeaderGenerateOptions = {}
  ): GeneratedCFiles {
    const langs = options.targetLanguages || CHeaderGenerator.DEFAULT_LANGUAGES;
    const project = options.projectName || 'Magene C606 Smart Computer';
    const version = options.versionName || 'v2.0.0';
    const timestamp = new Date().toISOString();

    // ────────────────────────────────────────────────────────────────────────
    // 1. Generate strings_lang.h
    // ────────────────────────────────────────────────────────────────────────
    const headerLines: string[] = [
      '/**',
      ` * Auto-generated by glossa-cli (TASK-802)`,
      ` * Project: ${project}`,
      ` * Version: ${version}`,
      ` * Generated At: ${timestamp}`,
      ` * DO NOT EDIT DIRECTLY MANUALLY.`,
      ' */',
      '',
      '#ifndef GLOSSA_STRINGS_LANG_H',
      '#define GLOSSA_STRINGS_LANG_H',
      '',
      '#include <stddef.h>',
      '#include <stdint.h>',
      '',
      '#ifdef __cplusplus',
      'extern "C" {',
      '#endif',
      '',
      '/* Supported Firmware Languages */',
      'typedef enum {',
    ];

    langs.forEach((l, idx) => {
      headerLines.push(`    ${CHeaderGenerator.toLangEnum(l)} = ${idx},`);
    });
    headerLines.push('    LANG_MAX_COUNT');
    headerLines.push('} firmware_lang_t;');
    headerLines.push('');

    headerLines.push('/* Firmware String Macro Identifiers */');
    headerLines.push('typedef enum {');
    terms.forEach((t, idx) => {
      headerLines.push(`    ${t.kw} = ${idx}, /* ${CHeaderGenerator.escapeCString(t.zhCn)} */`);
    });
    headerLines.push('    STRING_KW_MAX_COUNT');
    headerLines.push('} string_kw_id_t;');
    headerLines.push('');

    headerLines.push('/**');
    headerLines.push(' * Retrieve localized string pointer by KW id and language');
    headerLines.push(' * Returns pointer to ROM string, or empty string "" if out of bounds');
    headerLines.push(' */');
    headerLines.push('const char* get_firmware_string(string_kw_id_t id, firmware_lang_t lang);');
    headerLines.push('');
    headerLines.push('#ifdef __cplusplus');
    headerLines.push('}');
    headerLines.push('#endif');
    headerLines.push('');
    headerLines.push('#endif /* GLOSSA_STRINGS_LANG_H */');
    headerLines.push('');

    // ────────────────────────────────────────────────────────────────────────
    // 2. Generate strings_lang.c
    // ────────────────────────────────────────────────────────────────────────
    const sourceLines: string[] = [
      '/**',
      ` * Auto-generated by glossa-cli (TASK-802)`,
      ` * Project: ${project}`,
      ` * Version: ${version}`,
      ` * Generated At: ${timestamp}`,
      ' */',
      '',
      '#include "strings_lang.h"',
      '',
      `/* 2D Constant ROM String Table [${terms.length} KWs x ${langs.length} Languages] */`,
      `static const char* const g_firmware_strings[STRING_KW_MAX_COUNT][LANG_MAX_COUNT] = {`,
    ];

    terms.forEach((t) => {
      sourceLines.push(`    /* ${t.kw} (${CHeaderGenerator.escapeCString(t.zhCn)}) */`);
      sourceLines.push('    {');
      langs.forEach((l) => {
        let text = t.translations[l] || (l === 'zh' ? t.zhCn : '');
        // fallback to zhCn if translation is empty
        if (!text && l !== 'zh') {
          text = t.translations['en'] || t.zhCn;
        }
        const escaped = CHeaderGenerator.escapeCString(text);
        sourceLines.push(`        "${escaped}", /* ${CHeaderGenerator.toLangEnum(l)} */`);
      });
      sourceLines.push('    },');
    });

    sourceLines.push('};');
    sourceLines.push('');
    sourceLines.push('const char* get_firmware_string(string_kw_id_t id, firmware_lang_t lang) {');
    sourceLines.push('    if ((uint32_t)id >= (uint32_t)STRING_KW_MAX_COUNT) {');
    sourceLines.push('        return "";');
    sourceLines.push('    }');
    sourceLines.push('    if ((uint32_t)lang >= (uint32_t)LANG_MAX_COUNT) {');
    sourceLines.push('        return "";');
    sourceLines.push('    }');
    sourceLines.push('    const char* str = g_firmware_strings[id][lang];');
    sourceLines.push('    return (str != NULL) ? str : "";');
    sourceLines.push('}');
    sourceLines.push('');

    return {
      headerContent: headerLines.join('\n'),
      sourceContent: sourceLines.join('\n'),
    };
  }
}
