import { MobileTermInput } from './android-generator';

/**
 * iOS Localizable.strings Generator (TASK-803)
 * Compiles strings into *.lproj/Localizable.strings
 */
export class IOSGenerator {
  /**
   * Escape iOS Strings format: "KW" = "Value";
   */
  public static escapeIosString(str: string): string {
    if (!str) return '';
    return str
      .replace(/\\/g, '\\\\')
      .replace(/"/g, '\\"')
      .replace(/\r?\n/g, '\\n');
  }

  /**
   * Normalize language code to iOS .lproj folder name
   */
  public static toIosLprojName(lang: string): string {
    const map: Record<string, string> = {
      zh: 'zh-Hans',
      'zh-cn': 'zh-Hans',
      'zh-tw': 'zh-Hant',
      en: 'en',
      de: 'de',
      fr: 'fr',
      es: 'es',
      it: 'it',
      ja: 'ja',
      ko: 'ko',
      ru: 'ru',
      nl: 'nl',
      pl: 'pl',
    };
    return `${map[lang.toLowerCase()] || lang}.lproj`;
  }

  /**
   * Generate Localizable.strings content for a specific language
   */
  public generateStrings(terms: MobileTermInput[], lang: string): string {
    const lines: string[] = [
      '/*',
      ' * Auto-generated by glossa-cli (TASK-803)',
      ` * Language: ${lang}`,
      ' * Localizable.strings',
      ' */',
      '',
    ];

    for (const term of terms) {
      let text = term.translations[lang];
      if (text === undefined || text === '') {
        text = lang === 'zh' ? term.zhCn : term.translations['en'] || term.zhCn;
      }
      const escapedKey = IOSGenerator.escapeIosString(term.kw);
      const escapedValue = IOSGenerator.escapeIosString(text);
      lines.push(`/* ${IOSGenerator.escapeIosString(term.zhCn)} */`);
      lines.push(`"${escapedKey}" = "${escapedValue}";`);
      lines.push('');
    }

    return lines.join('\n');
  }
}
